### ISSUE TITLE
Notification when upload is finished

### ISSUE THREAD

**Issue by florianluediger** [instantshare/instantshare#3]
At the moment you don't know when the upload finished and the link is copied to the clipboard, so a notification should be added.

To Do:
- [x] Acoustic Notifications
- [ ] Notification Popups

**Comment by dtext** [comment]
I definitely like the notification sound a lot, but I think there should also be a visual notification. This would be helpful, as there is no way to know if your screenshot is uploaded when you have your speakers muted or something like that.

At least on linux, there is `libnotify`, which provides a CLI: `notify-send`. On windows, we could provide another backend for this. It would be nice to get the new Windows 10 notifications working.

**Comment by denniseffing** [comment]
👍 for visual notifications. 

Windows: Definitely use the Windows 10 notifications if possible. (Plus solution for Windows 7?)

**Comment by dtext** [comment]
As instantshare runs in the background most of the time, an error notification would also be nice. I could contribute something that I threw together quickly, but actually sounds decent. If you want, I can add that to the pull request when the rest of this is done.

Edit: Since we already have an acoustic notification for upload success, I added the error sound while making a small fix (48447c407d2c6ca25ad490a4b76432501ad44e0e). The acoustic part of this is done, so we can focus the PR on the visual notifications.

**Comment by dtext** [comment]
For windows 10, I ran across this: https://github.com/jithurjacob/Windows-10-Toast-Notifications
Maybe this could be helpful?
